---
language: python
python: "2.7"
sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

script:
  - pwd
  - ls
  - ls test/ 
  - ansible-galaxy install -r $(pwd)/test/requirements.yml --roles-path=$(pwd)/test/roles/
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
